vim.cmd("set clipboard+=unnamedplus")
vim.cmd("filetype plugin on")
vim.cmd("syntax on")
vim.cmd("filetype indent on")
vim.cmd("set number")
vim.cmd("set relativenumber")
--vim.cmd("set spell")
vim.cmd("set incsearch")
vim.cmd("set hlsearch")
